### ISSUE TITLE
Gradle parser is not working on Windows systems

### ISSUE THREAD

**Issue by n1xx1** [ionic-team/capacitor-configure#62]
https://github.com/ionic-team/capacitor-configure/blob/main/packages/project/src/android/gradle-file.ts#L207

Here, on windows, java expect the paths to be delimited by `;`, not `:`. Otherwise a Fatal error is thrown with this exception:

```
run android gradle
Fatal error: Error running command
Error: Unable to load or parse gradle file: Error: Could not find or load main class com.capacitorjs.gradle.Parse
Caused by: java.lang.ClassNotFoundException: com.capacitorjs.gradle.Parse
    at GradleFile.parse (C:\Users\MyUser\MyProject\node_modules\@capacitor\configure\node_modules\@capacitor\project\dist\android\gradle-file.js:173:19)    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GradleFile.replaceProperties (C:\Users\MyUser\MyProject\node_modules\@capacitor\configure\node_modules\@capacitor\project\dist\android\gradle-f
ile.js:28:9)
    at async execute (C:\Users\MyUser\MyProject\node_modules\@capacitor\configure\dist\operations\android\gradle.js:12:13)
    at async executeOperations (C:\Users\MyUser\MyProject\node_modules\@capacitor\configure\dist\tasks\run.js:74:9)
    at async runCommand (C:\Users\MyUser\MyProject\node_modules\@capacitor\configure\dist\tasks\run.js:34:9)
    at async C:\Users\MyUser\MyProject\node_modules\@capacitor\configure\dist\index.js:52:13
    at async Command.<anonymous> (C:\Users\MyUser\MyProject\node_modules\@capacitor\configure\dist\util\cli.js:31:13)
```

**Comment by kentora** [comment]
Could we get a release on this? :)

**Comment by leobaccili** [comment]
Yeah, this is very helpful

**Comment by mlynch** [comment]
Should be live now in 2.0.9. Give it a try and let me know how it works for you!

**Comment by leobaccili** [comment]
Worked perfectly for me, you're awesome!
